config/routes.rb
Rails.application.routes.draw do

 

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'gadgets/index'

  get 'editor/index'
  get 'editor/editor_01'

  get 'gift_guide/index'
  get 'gift_guide/gift_guide_01'
  
  get 'blog/index'
  get 'blog/blog_01'

  # get 'featured/index'
  # get 'featured/featured_01'

  get 'deals/promo_codes'
  get 'deals/coupons'
  get 'deals/quick_search'
  get 'deals/promotions'
  get 'deals/codes'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts
  root 'posts#index'

  resources :gadgets
  # root 'gadgets#index'
  # root 'gadgets#index_02'

  resources :recommends
  # root 'recommends#index'
  
  
end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :user

  def self.search_by(search_term)
    where("LOWER(re_title) LIKE :search_term",
      search_term: "%#{search_term.downcase}%")
  end
end

app/controllers/recommends_controller.rb
class RecommendsController < ApplicationController

  before_action :find_recommend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource


  def index
    @recommends = Recommend.all.order("created_at DESC")
    if params[:search]
       @search_term = params[:search]
       @recommends = @recommends.search_by(@search_term)
    end
  end

  def show
  end

  def new
    @recommend = current_user.recommends.build
  end

  def create
    @recommend = current_user.recommends.build(recommend_params)
      if @recommend.save
        redirect_to @recommend
      else
        render 'new'
      end
  end

  def edit
  end

  def update
    if @recommend.update(recommend_params)
      redirect_to @recommend
    else
      render 'edit'
    end
  end

  def destroy
    @recommend.destroy
      redirect_to '/recommends/'
  end

  private

  def find_recommend
    @recommend = Recommend.find(params[:id])
  end

  def recommend_params
    params.require(:recommend).permit(:re_filter, :re_title, :sub_intro, :re_intro, :re_image, :sub_number_01, :sub_number_01, :sub_number_01,
                                      :sub_number_02, :sub_number_03, :sub_number_04, :sub_number_05, :sub_number_06, :sub_number_07, :sub_number_08,
                                      :sub_number_09, :sub_number_10, :sub_image_01, :sub_image_02, :sub_image_03, :sub_image_04, :sub_image_05, :sub_image_06,
                                      :sub_image_07, :sub_image_08, :sub_image_09, :sub_image_10, :sub_title_01, :sub_title_02, :sub_title_03, :sub_title_04, :sub_title_05,
                                      :sub_title_06, :sub_title_07, :sub_title_08, :sub_title_09, :sub_title_10, :sub_intro_01, :sub_intro_02, :sub_intro_03, :sub_intro_04,
                                      :sub_intro_05, :sub_intro_06, :sub_intro_07, :sub_intro_08, :sub_intro_09, :sub_intro_10, :sub_source_01, :sub_source_02, :sub_source_03,
                                      :sub_source_04, :sub_source_05, :sub_source_06, :sub_source_07, :sub_source_08, :sub_source_09, :sub_source_10, :sub_price_01, :sub_price_02,
                                      :sub_price_03, :sub_price_04, :sub_price_05, :sub_price_06, :sub_price_07, :sub_price_08, :sub_price_09, :sub_price_10, :sub_link_01,
                                      :sub_link_02, :sub_link_03, :sub_link_04, :sub_link_05, :sub_link_06, :sub_link_07, :sub_link_08, :sub_link_09, :sub_link_10, :sub_youtube_01,
                                      :sub_youtube_02, :sub_youtube_03, :sub_youtube_04, :sub_youtube_05, :sub_youtube_06, :sub_youtube_07, :sub_youtube_08, :sub_youtube_09, :sub_youtube_10)
  end
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/views/recommends/_body.html.erb
<% @recommends.each do |recommend| %>
  <div class="filter-node" data-filter='["<%= recommend.re_filter %>"]'>
    <div class="inner">
      <%= link_to (image_tag recommend.re_image), recommend %>
      <em><%= recommend.re_filter %></em>
        <a href="/featured/featured_01">
        <h3><%= link_to recommend.re_title, recommend %></h3>
        <p><%= link_to recommend.re_intro, recommend %></p>
        </a>
    </div>
    <% if can? :update, recommend %>
      <div class="btn clearfix admin">
        <em><%= link_to "Edit", edit_recommend_path(recommend) %></em><%= link_to "Delete", recommend_path(recommend), method: :delete, data: {confirm: "Are you sure?"}%>
      </div>
    <% end %>
  </div>
<% end %>

<div class="filter-node" data-filter='["travel"]'>
  <div class="inner">
    <a href="/featured/featured_01"><img src="https://i.pinimg.com/564x/4c/14/ae/4c14ae6547540a6dc4d51d5061c4d731.jpg" alt="" /></a>
    <em>Travel</em>
      <a href="/featured/featured_01">
      <h3>Comfortable Travel Pillow(Part.1)</h3>
      <p>I`d like to share 10 Comfortable “Travel Pillow” that will make you have a sweet dream while you traveling today.</p>
      </a>
  </div>
</div>

<div class="filter-node" data-filter='["tech"]'>
  <div class="inner">
    <a href="/featured/featured_01"><img src="https://images.unsplash.com/photo-1549490148-237260354488?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="" /></a>
    <em>TECH+</em>
      <a href="/featured/featured_01">
      <h3>10 Cool & Clever Finds (smarthome)</h3>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
      </a>
  </div>
</div>

<div class="filter-node" data-filter='["tech"," vintage"]'>
  <div class="inner">
    <a href="/featured/featured_01"><img src="https://images.unsplash.com/photo-1549554164-dbf2a3ddf41f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="" /></a>
      <em>TECH+</em>
      <a href="/featured/featured_01">
        <h3>10 Cool & Clever Finds (smarthome)</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
      </a>
  </div>
</div>

<div class="filter-node" data-filter='["smarthome"," vintage"]'>
  <div class="inner">
    <a href="/featured/featured_01"><img src="https://images.unsplash.com/photo-1549650558-eaca848e241b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="" /></a>
      <em>TECH+</em>
      <a href="#n">
      <h3>10 Cool & Clever Finds(kitchen)</h3>
      <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
    </a>
  </div>
</div>

<div class="filter-node" data-filter='["geeky"," vintage"]'>
  <div class="inner">
    <a href="curation_detail.html"><img src="https://images.unsplash.com/photo-1549506767-edd4ca83c7f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="" /></a>
      <em>TECH+</em>
      <a href="#n">
      <h3>10 Cool & Clever Finds(geeky)</h3>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
    </a>
  </div>
</div>

app/views/recommends/_form.html.erb
<div class="layout">
  <div class="wrap">
    <div class="input_wrap">
      <%= simple_form_for @recommend do |f| %>
        <div class="input_header clearfix ">
          <div class="input_header_box ib_comm ">
            <p>Main</p>
            <%= f.input :re_filter %>
            <%= f.input :re_title %>
            <%= f.input :re_intro %>
            <%= f.input :sub_intro %>
            <%= f.input :re_image %>
          </div>
          <div class="input_image">
          </div>
        </div>

        <div class="input_body_left ib_comm clearfix">
          <div class="input_box">
            <p>Post Num.1</p>
            <%= f.input :sub_image_01 %>
            <%= f.input :sub_title_01 %>
            <%= f.input :sub_intro_01 %>
            <%= f.input :sub_price_01 %>
            <%= f.input :sub_source_01 %>
            <%= f.input :sub_link_01 %>
            <%= f.input :sub_youtube_01 %>
          </div>
          <div class="input_box">
            <p>Post Num.2</p>
            <%= f.input :sub_image_02 %>
            <%= f.input :sub_title_02 %>
            <%= f.input :sub_intro_02 %>
            <%= f.input :sub_price_02 %>
            <%= f.input :sub_source_02 %>
            <%= f.input :sub_link_02 %>
            <%= f.input :sub_youtube_02 %>
          </div>
          <div class="input_box">
            <p>Post Num.3</p>
            <%= f.input :sub_image_03 %>
            <%= f.input :sub_title_03 %>
            <%= f.input :sub_intro_03 %>
            <%= f.input :sub_price_03 %>
            <%= f.input :sub_source_03 %>
            <%= f.input :sub_link_03 %>
            <%= f.input :sub_youtube_03 %>
          </div>
          <div class="input_box">
            <p>Post Num.4</p>
            <%= f.input :sub_image_04 %>
            <%= f.input :sub_title_04 %>
            <%= f.input :sub_intro_04 %>
            <%= f.input :sub_price_04 %>
            <%= f.input :sub_source_04 %>
            <%= f.input :sub_link_04 %>
            <%= f.input :sub_youtube_04 %>
          </div>
          <div class="input_box">
            <p>Post Num.5</p>
            <%= f.input :sub_image_05 %>
            <%= f.input :sub_title_05 %>
            <%= f.input :sub_intro_05 %>
            <%= f.input :sub_price_05 %>
            <%= f.input :sub_source_05 %>
            <%= f.input :sub_link_05 %>
            <%= f.input :sub_youtube_05 %>
          </div>
        </div>

        <div class="input_body_right ib_comm clearfix">
          <div class="input_box">
            <p>Post Num.6</p>
            <%= f.input :sub_image_06 %>
            <%= f.input :sub_title_06 %>
            <%= f.input :sub_intro_06 %>
            <%= f.input :sub_price_06 %>
            <%= f.input :sub_source_06 %>
            <%= f.input :sub_link_06 %>
            <%= f.input :sub_youtube_06 %>
          </div>
          <div class="input_box">
            <p>Post Num.7</p>
            <%= f.input :sub_image_07 %>
            <%= f.input :sub_title_07 %>
            <%= f.input :sub_intro_07 %>
            <%= f.input :sub_price_07 %>
            <%= f.input :sub_source_07 %>
            <%= f.input :sub_link_07 %>
            <%= f.input :sub_youtube_07 %>
          </div>
          <div class="input_box">
            <p>Post Num.8</p>
            <%= f.input :sub_image_08 %>
            <%= f.input :sub_title_08 %>
            <%= f.input :sub_intro_08 %>
            <%= f.input :sub_price_08 %>
            <%= f.input :sub_source_08 %>
            <%= f.input :sub_link_08 %>
            <%= f.input :sub_youtube_08 %>
          </div>
          <div class="input_box">
            <p>Post Num.9</p>
            <%= f.input :sub_image_09 %>
            <%= f.input :sub_title_09 %>
            <%= f.input :sub_intro_09 %>
            <%= f.input :sub_price_09 %>
            <%= f.input :sub_source_09 %>
            <%= f.input :sub_link_09 %>
            <%= f.input :sub_youtube_09 %>
          </div>
          <div class="input_box">
            <p>Post Num.10</p>
            <%= f.input :sub_image_10 %>
            <%= f.input :sub_title_10 %>
            <%= f.input :sub_intro_10 %>
            <%= f.input :sub_price_10 %>
            <%= f.input :sub_source_10 %>
            <%= f.input :sub_link_10 %>
            <%= f.input :sub_youtube_10 %>
          </div>
        </div>
        <div class="input_footer">
          <%= f.button :submit %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/recommends/_jquery.js.erb
  //Begin sticky&following sidebar
  $(function () {
    var offset = $(".featured .sm_pc").offset();
    var topPadding = 100;
    $(window).scroll(function () {
        if ($(window).scrollTop() > offset.top) {
            $(".featured .sm_pc").addClass("on");

        } else {
            $(".featured .sm_pc").removeClass("on");

          };
      });
   });
  //End
  
  //Begin filter on featured
  var example = new DataFilterJS({
    filterGroup: '.filter-group',
    filterNode: '.filter-node',
    filterButtonGroup: '.filter-search',
    transitionSpeed: '0'
  });

  function DataFilterJS(config){
    // define variables
    var filterGroup = config.filterGroup;
    var filterNode = config.filterNode;
    var filterButtonGroup = config.filterButtonGroup;
    var transitionSpeed = config.transitionSpeed;
    var filter_group = $(filterGroup);
    var filter_node = $(filterGroup+' > '+filterNode);
    var search_val = $(filterButtonGroup+'> '+'input[type="text"]').value;
    $(filterGroup+', '+filterNode+', '+filterNode+'.filter-me').css({"transition":"all "+transitionSpeed});
    
    // (Button) Data Filter Function
    $(filterButtonGroup+' .filter-button').on('click', function(e) {
      var eventFilter = e.currentTarget.attributes[1].nodeValue;
       // Loop through Filter Nodes on Button Click
       $.each(filter_node, function(i, v) {
          if(eventFilter == "*") {
            filter_node[i].classList.remove('filter-me');
          } else if(filter_node[i].getAttribute('data-filter').includes(eventFilter) == false) {
            filter_node[i].classList.add('filter-me')
          } else {filter_node[i].classList.remove('filter-me');}
       });
    }); // end click event

    // (Keystroke) Data Filter Function    
    $(filterButtonGroup+' > input[type="text"]').on('keypress keydown keyup', function(e, fnd) {
      // Loop through Filter Nodes on Keystroke
      $.each($(filterNode), function(i, v) {
        var node = v.getAttribute("data-filter").toString().toUpperCase();
        var search_string = $(filterButtonGroup+' > '+'input[type="text"]').val().toUpperCase();
        //console.log(node.getAttribute('data-filter'));
        if(node.includes(search_string) == false) {
          v.classList.add('filter-me');
        } else {v.classList.remove('filter-me');}
      }); // end each
    }); // end keypress
  }
  //End filter on featured

  //Begin show menu on featured
    var document_h = $(document).height();
  //console.log(document_h);
  $(".featured .sm_mobile").height(document_h);
  
  $(".featured .gnb_open").on("click", function(){
    $(".featured .gnb_kbg").fadeIn(300);
    $(".featured .sm_mobile").animate({
      right : 0
    },300);

  });
  $(".featured .gnb_kbg").on("click", function(){
    $(".featured .gnb_kbg").fadeOut(300);
    $(".featured .sm_mobile").animate({
      right : -800
    },300);
  });
  $(".featured .gnb_close").on("click", function(){
    $(".featured .gnb_kbg").fadeOut(300);
    $(".featured .sm_mobile").animate({
      right : -800
    },300);
  });
  //End show menu on featured

app/views/recommends/edit.html.erb
<%= render 'form' %>

app/views/recommends/index.html.erb
<div class="layout"><!--layout-->
    
  <%= render 'posts/header' %>
    
  <div class="wrap">
    
      <div class="cu_sub_nav">
        <ul class="clearfix">
          <li><a class="active" href="/featured/index">Featured</a></li>
          <!--<li><a href="/gift_guide/index">Gift Guide</a></li>-->
          <li><a href="/editor/index">Editor's Pick</a></li>
          <li><a href="/blog/index">Blog</a></li>
        </ul>
      </div>

      <div class="featured common_layout clearfix">
      
        <div class="lt_cnt deal">
          <h2>Featured</h2>
          <div class="note">
            <ul>
              <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</li>
            </ul>
          </div>
          <button class="gnb_open"><img src="<%=asset_path 'open_black.png' %>" alt="모바일 메뉴 열기" /></button>
          <div class="sm_pc">
            
           <!--  <div class="search_bar">
              <input type="text" class="form-control" placeholder="Search...">
              <img src="<%=asset_path 'search.png' %>" alt="" />
            </div>
            
            <%= form_for "",url: recommends_path, role: "search", method: :get do %>
              <%= text_field_tag :search, @search_term,placeholder: "Search..." %>
            <% end %> -->

            <ul class="filter-search">
              <li><button class="filter-button btn btn-md btn-primary" data-filter="*">All Featured</button></li>
              <li><button class="filter-button btn btn-md white-text" data-filter="tech">Tech+</button></li>
              <li><button class="filter-button btn btn-md" data-filter="smarthome">Smart Home</button></li>
              <li><button class="filter-button btn btn-md" data-filter="kitchen">Kitchen&Home</button></li>
              <li><button class="filter-button btn btn-md white-text" data-filter="fashion">Fashion</button></li>
              <li><button class="filter-button btn btn-md white-text" data-filter="travel">Travel</button></li>
              <li><button class="filter-button btn btn-md white-text" data-filter="geeky">Geeky</button></li>
              <% if can? :update, @recommend %>
                <li><%= link_to "Add Featured", new_recommend_path, :class => "filter-button" %></li>
              <% end %>
            </ul>
          </div>
          
          <div class="sm_mobile">
            <ul class="filter-search">
              <li><button class="filter-button btn btn-md btn-primary" data-filter="*">All Featured</button></li>
              <li><button class="filter-button btn btn-md white-text" data-filter="tech">Tech+</button></li>
              <li><button class="filter-button btn btn-md" data-filter="smarthome">Smart Home</button></li>
              <li><button class="filter-button btn btn-md" data-filter="kitchen">Kitchen&Home</button></li>
              <li><button class="filter-button btn btn-md white-text" data-filter="fashion">Fashion</button></li>
              <li><button class="filter-button btn btn-md white-text" data-filter="travel">Travel</button></li>
              <li><button class="filter-button btn btn-md white-text" data-filter="geeky">Geeky</button></li>
            </ul>
            <button class="gnb_close"><img src="<%=asset_path 'close_white.png' %>" alt="모바일 메뉴 닫기" />
          </div>
        
        </div><!--./lt_cnt-->
        <div class="gnb_kbg"></div>
        
        <div class="rt_cnt">
          <h2>We Love </h2>
          
          <!--
          <div class="gift_guide clearfix">
            <a href="/gift_guide/gift_guide_01">
              <div class="gift_box card_01">
                <div class="inner">
                  <p>FOR <span>HIM<span></p>
                </div>
              </div>
            </a>
          
            <a href="/gift_guide/gift_guide_01">
              <div class="gift_box card_02">
                <div class="inner">
                  <p>FOR <span>HER<span></p>
                </div>
              </div>
            </a>
          
            <a href="/gift_guide/gift_guide_01">
              <div class="gift_box card_03">
                <div class="inner">
                  <p>FOR <span>KIDS<span></p>
                </div>
              </div>
            </a>
          </div>
          -->

          <div class="filter-group clearfix">
            <%= render 'recommends/body' %>
          </div>

        </div><!--./rt_cnt-->
      </div><!--./featured-->
  </div><!--./wrap-->
</div><!--./layout-->
<script> 
  <%= render(:partial => 'jquery', :handlers => [:erb], :formats => [:js]) %>
</script>

app/views/recommends/new.html.erb
<%= render 'form' %>