config/routes.rb
Rails.application.routes.draw do

 

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'gadgets/index'

  get 'editor/index'
  get 'editor/editor_01'

  get 'gift_guide/index'
  get 'gift_guide/gift_guide_01'
  
  get 'blog/index'
  get 'blog/blog_01'

  # get 'featured/index'
  # get 'featured/featured_01'

  get 'deals/promo_codes'
  get 'deals/coupons'
  get 'deals/quick_search'
  get 'deals/promotions'
  get 'deals/codes'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts
  root 'posts#index'

  resources :gadgets
  # root 'gadgets#index'
  # root 'gadgets#index_02'

  resources :recommends
  # root 'recommends#index'
  
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
      can :access, :rails_admin
      can :read, :dashboard   
    else
      can :read, :all
    end
     

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :gadgets
end

app/models/gadget.rb
class Gadget < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  
end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :user

  def self.search_by(search_term)
    where("LOWER(re_title) LIKE :search_term",
      search_term: "%#{search_term.downcase}%")
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gadgets
  has_many :recommends


end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def promo_codes
  end

  def coupons
  end

  def quick_search
  end

  def promotions
  end
end

app/controllers/editor_controller.rb
class EditorController < ApplicationController
  def index
  end

  def editor_01
  end
end

app/controllers/featured_controller.rb
class FeaturedController < ApplicationController

  def index
  end

  def featured_01
  end
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController

  before_action :find_gadget, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  def index
    if params[:category].blank?
     @gadgets = Gadget.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @gadgets = Gadget.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @gadget = current_user.gadgets.build
  end

  def create
    @gadget = current_user.gadgets.build(gadget_params)
    if @gadget.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @gadget.update(gadget_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @gadget.destroy
    redirect_to root_path
  end

  private

  def find_gadget
    @gadget = Gadget.find(params[:id])
  end

  def gadget_params
    params.require(:gadget).permit(:gad_title, :gad_intro, :gad_price, :gad_link, :gad_img, :gad_youtube, :category_id)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
    @gadgets = Gadget.all.order("created_at DESC")
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_params
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
      @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :brand, :description, :price, :image, :link)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/featured_helper.rb
module FeaturedHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/helpers/gift_guide_helper.rb
module GiftGuideHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/views/gadgets/_form.html.erb
<%= simple_form_for @gadget do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :name, {promt:"Choose a category"} %>
  <%= f.input :gad_title %>
  <%= f.input :gad_intro %>
  <%= f.input :gad_img %>
  <%= f.input :gad_price %>
  <%= f.input :gad_link %>
  <%= f.input :gad_youtube %>

  <%= f.button :submit %>
<% end %>

app/views/gadgets/_gadgets.js.erb
//Begin show side menu on gadgets page
var document_gadgets = $(document).height();
//console.log(document_gadgets);
$(".gadgets_wrapper main section#filter").height(document_gadgets);

$(".gadgets_wrapper main .gnb_open").on("click", function(){
  $(".gadgets_wrapper main .gnb_kbg").fadeIn(300);
  $(".gadgets_wrapper main section#filter").animate({
    right : 0
  },300);
});

$(".gadgets_wrapper main .gnb_close").on("click", function(){
  $(".gadgets_wrapper main .gnb_kbg").fadeOut(300);
  $(".gadgets_wrapper main section#filter").animate({
    right : -800
  },300);
});

 $(".gadgets_wrapper main .gnb_kbg").on("click", function(){
  $(".gadgets_wrapper main .gnb_kbg").fadeOut(300);
  $(".gadgets_wrapper main section#filter").animate({
    right : -800
  },300);
});

$(".gadgets_wrapper main .gnb_open_b").on("click", function(){
  $(".gadgets_wrapper main .gnb_kbg").fadeIn(300);
  $(".gadgets_wrapper main section#filter").animate({
    right : 0
  },300);
});

$(".gadgets_wrapper main .gnb_kbg_b").on("click", function(){
  $(".gadgets_wrapper main .gnb_kbg").fadeOut(300);
  $(".gadgets_wrapper main section#filter").animate({
    right : -800
  },300);
});   
//End

app/views/gadgets/_header.html.erb
<header>
  <div class="wrap">
    <button class="gnb_open2"><img src="<%=asset_path 'more_black.png' %>" alt="open mobile menu" /></button>
    <div class="gnb_pc clearfix">
      <a href="/"><img class="oh_logo" src="<%=asset_path 'oh_logo.jpg' %>" alt="ohigottabuythis" /></a>
      <!--<h1><a href="/">Oh,I GOTTA BUY THIS</a></h1>-->

      <div class="visual">
        <h1><a href="/">Oh,I GOTTA BUY THIS</a></h1>
      </div>

      <ul class="clearfix sub_index_02">
        <li><a href="/featured/index">FEATURED<span>,</span></a></li>
        <li><a href="/deals/promo_codes">DEALS <em>of Amazon</em></a></li>
      </ul>      
    </div>
    
    
    <div class="gnb_m">
      <ul class="clearfix">
        <li><a href="/">HOME<span>,</span></a></li> 
        <li><a href="/featured/index">FEATURED<span>,</span></a></li>
        <li><a href="/deals/promo_codes">DEALS <em>of Amazon</em></a></li>
      </ul>
      <button class="gnb_close"><img src="<%=asset_path 'close_white.png' %>" alt="모바일 메뉴 닫기" />
    </div>
   
</header>

app/views/gadgets/edit.html.erb
<h1>This is Edit Gadgets page</h1>
<%= render 'form' %>

app/views/gadgets/index.html.erb
<div class="layout"><!--layout-->

  <%= render 'posts/header' %>
    
  <!-- for play youtube video-->
  <div class="overlay-video">
    <div class="videoWrapperExt">
      <div class="videoWrapper">
        <div class="video_close"></div>
        <iframe id="player" src="" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>        
   </div>
  
  <div class="gadgets_wrapper">
    <div class="wrap">
      <main class="clearfix">
        
          <button class="gnb_open"><img src="<%=asset_path 'open_black.png' %>" alt="open" /></button>
          <button class="gnb_open_b"><img src="<%=asset_path 'open_black.png' %>" alt="open" /></button>
          <section id="filter">
            <div class="ui-group">
              <label>Category</label>
              <ul>
                <li><%= link_to "All Gadgets", gadgets_path %></li>
                <% Category.all.each do |category| %>
                  <li><%= link_to category.name, gadgets_path(category: category.name) %></li>
                <% end %>               
                <% if can? :update, @gadgets %>
                  <li><%= link_to "Add New Gadgets", new_gadget_path %></li>
                  <% if user_signed_in? %>
                    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                  <% else %>
                   <li><%= link_to "Log in", new_user_session_path %></li>
                   <!--<li><%= link_to "Sign up", new_user_registration_path %></li>-->
                  <% end %>
                <% end %>
              </ul>
              <button class="gnb_close"><img src="<%=asset_path 'close_white.png' %>" alt="close menu" /></button>
            </div>
          </section>
          <div class="gnb_kbg"></div>

          <div class="on_gadgets">
            
              <div class="current_category">
                <% if params[:category].present? %>
                  <p><%= params[:category] %></h2>
                <% else %>
                  <p>all gadgets</p>
                <% end %>
              </div>
              
              <div class="card_wrap clearfix" >
                <% @gadgets.each do |gadget| %>
                  <div class="card with-photo">
                    <div class="card-header">
                     <a target="_blank" href="<%= gadget.gad_link %>"><img src="<%= gadget.gad_img %>" alt=""></a>
                    </div>
                    
                    <section class="card-body">
                      <div class="js-overlay-start start" data-url= "<%= gadget.gad_youtube %>">
                        <button><img src="<%=asset_path 'youtube_02.png' %>" alt="" /></button>
                      </div>

                     
                      <h4><a target="_blank" href="<%= gadget.gad_link %>"><%= gadget.gad_title %></a></h4>
                      <p><%= gadget.gad_intro %></p>
                      <div class="btn clearfix">
                        <em>$<%= gadget.gad_price %></em><a target="_blank" href="<%= gadget.gad_link %>">Buy Now</a>
                      </div>              
                    </section>
                  </div>
                <% end %>
             </div><!--./card_wrap-->
         </div><!--./on_gadgets-->
        </main>
      </div><!--./wrap-->
  </div><!--./gadgets_wrapper-->
</div><!--./layout-->
<script>
  <%= render(:partial => 'gadgets', :handlers => [:erb], :formats => [:js]) %>
</script>

app/views/gadgets/index.js.erb
$('#gadgets').append('<%= j render(@gadgets) %>');
<% if @gadgets.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@gadgets) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/gadgets/new.html.erb
<h1>This is New Gadgets page</h1>
<%= render 'form' %>

app/views/gadgets/show.html.erb
<img src="<%= @gadget.gad_img %>" alt="" />
<h1><%= @gadget.gad_title %></h1>
<p><%= @gadget.gad_intro %></p>
<a href="<%= @gadget.gad_youtube %>">Youtube</a>
<p>$<%= @gadget.gad_price %></p>
<a href="<%= @gadget.gad_link %>">Buy Now</a>
<p><%= @gadget.user.name %></p>
<br />
<br />
<%= link_to "HOME", root_path %>
<%= link_to "Edit", edit_gadget_path(@gadget) %>
<%= link_to "Delete", gadget_path(@gadget), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :image %>
  <%= f.input :description %>
  <%= f.input :brand %>
  <%= f.input :price %>
  <%= f.input :link %>

  <%= f.button :submit %>
<% end %>

app/views/posts/_header.html.erb
<header>
  <div class="wrap">
    <button class="gnb_open2"><img src="<%=asset_path 'more_black.png' %>" alt="open mobile menu" /></button>
    <div class="gnb_pc clearfix">
      <a href="/"><img class="oh_logo" src="<%=asset_path 'oh_logo.jpg' %>" alt="ohigottabuythis" /></a>

      <div class="visual">
        <h1><a href="/"><img src="/assets/visual_01.jpg" alt="ohigottabuythis" /></a></h1>
      </div>

      <ul class="clearfix">
        <li><a href="/gadgets/index">CATEGORY<span>,</span></a></li>
        <li><a href="/recommends/">FEATURED<span>,</span></a></li>
        <li><a href="/deals/promo_codes">DEALS <em>of Amazon</em></a></li>
      </ul>      
    </div>
    
    <div class="gnb_m">
      
      <div class="membership">
        <ul class="clearfix">
          <% if can? :update, @gadget %>
            <% if user_signed_in? %>
             <p>Hello, <%= current_user.name %><p>
             <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
            <% else %>
             <li><%= link_to "SIGN IN", new_user_session_path %></li>
             <li><%= link_to "SIGN UP", new_user_registration_path %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
      
      <ul class="clearfix">
        <li><a href="/">HOME<span>,</span></a></li> 
        <li><a href="/gadgets/index">CATEGORY<span>,</span></a></li>
        <li><a href="/recommends/">FEATURED<span>,</span></a></li>
        <li><a href="/deals/promo_codes">DEALS <em>of Amazon</em></a></li>
      </ul>
      <button class="gnb_close"><img src="<%=asset_path 'close_white.png' %>" alt="모바일 메뉴 닫기" /></button>
      
    </div><!--./gnb_m-->
  </div><!--./wrap-->
</header>

app/views/posts/_posts.js.erb
$(document).ready(function(){

  //for index 메뉴나타나기
    var document_h = $(document).height();
  //console.log(document_h);
  $("header .gnb_mobile").height(document_h);
  
  $("header .gnb_open").on("click", function(){
    $("header .gnb_kbg").fadeIn(300);
    $("header .gnb_mobile").animate({
      left : 0
    },300);
  });
  
  $("header .gnb_mobile>.gnb_close").on("click", function(){
    $("header .gnb_kbg").fadeOut(300);
    $("header .gnb_mobile").animate({
      left : -800
    },300); 
  });

  //Begin Change header when scrolling
    //스크롤 할때 header모양 변함
  var scrolling_pc;
  scroll_check();//함수실행
  
   //스크롤 될마다 실행
  $(window).scroll(function(){
    scroll_check();//함수실행
  });//scroll
  
   //함수선언
  function scroll_check(){
    scrolling_pc = $(window).scrollTop();
    //console.log(scrolling_pc);
    if(scrolling_pc > 0){
      $("header").addClass("on");
    }else{
      $("header").removeClass("on");
    }
  }
  //End


});

app/views/posts/edit.html.erb
<h1>This is Edit Page</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="layout"><!--layout-->
    
    <%= render 'header' %>
    
    <!-- for play youtube video-->
    <div class="overlay-video">
      <div class="videoWrapperExt">
        <div class="videoWrapper">
          <div class="video_close"></div>
          <iframe id="player" src="" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>        
    </div>

    <div class="gadgets">
      <div class="wrap">
        
        <div class="card_wrap clearfix">
          <% @gadgets.each do |gadget| %>
            <div class="card with-photo">
              <div class="card-header">
               <a target="_blank" href="<%= gadget.gad_link %>"><img src="<%= gadget.gad_img %>" alt=""></a>
              </div>
              
              <section class="card-body">
                
                <% if gadget.gad_youtube.present? %>
                  <div class="js-overlay-start start" data-url= "<%= gadget.gad_youtube %>">
                    <button><img src="<%=asset_path 'youtube_02.png' %>" alt="" /></button>
                  </div>
                <% end %>

                <h4><a target="_blank" href="<%= gadget.gad_link %>"><%= gadget.gad_title %></a></h4>
                <p><%= gadget.gad_intro %></p>
                <div class="btn clearfix">
                  <em>$<%= gadget.gad_price %></em><a target="_blank" href="<%= gadget.gad_link %>">Buy Now</a>
                </div>
                <% if can? :update, gadget %>
                  <div class="btn clearfix admin">
                    <em><%= link_to "Edit", edit_gadget_path(gadget) %></em><%= link_to "Delete", gadget_path(gadget), method: :delete, data: {confirm: "Are you sure?"}%>
                  </div>
                <% end %>
                
              </section>
            </div>
          <% end %>
        </div><!--./card_wrap-->

    </div><!--./wrap-->
  </div><!--./gadgets-->
</div><!--./layout-->

     

<script>
  <%= render(:partial => 'posts', :handlers => [:erb], :formats => [:js]) %>
</script>

app/views/posts/index.js.erb
$('#gadgets').append('<%= j render(@gadgets) %>');
<% if @gadgets.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@gadgets) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/posts/new.html.erb
<h1>This is New Post</h1>
<%= render 'form' %>

app/views/posts/posts.js.erb
$(document).ready(function(){

  //for index 메뉴나타나기
    var document_h = $(document).height();
  //console.log(document_h);
  $("header .gnb_mobile").height(document_h);
  
  $("header .gnb_open").on("click", function(){
    $("header .gnb_kbg").fadeIn(300);
    $("header .gnb_mobile").animate({
      left : 0
    },300);
  });
  
  $("header .gnb_mobile>.gnb_close").on("click", function(){
    $("header .gnb_kbg").fadeOut(300);
    $("header .gnb_mobile").animate({
      left : -800
    },300); 
  });

  //Begin Change header when scrolling
    //스크롤 할때 header모양 변함
  var scrolling_pc;
  scroll_check();//함수실행
  
   //스크롤 될마다 실행
  $(window).scroll(function(){
    scroll_check();//함수실행
  });//scroll
  
   //함수선언
  function scroll_check(){
    scrolling_pc = $(window).scrollTop();
    //console.log(scrolling_pc);
    if(scrolling_pc > 0){
      $("header").addClass("on");
    }else{
      $("header").removeClass("on");
    }
  }
  //End

});

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<img src="<%= @post.image %>" alt="" />
<p><%= @post.description %></p>
<p>by <%= @post.brand %></p>
<p>Price: <%= @post.price %></p>
<a href="<%= @post.link %>">GoTo</a>

<%= link_to "Home", root_path %>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm:"Are you sure?"}  %>